force-app/main/default/objects/Account/fields/Primary_Contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Primary Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Id</valueField>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Custom_Invoice__c/Custom_Invoice__c.object-meta.xml
<CustomObject>
    <label>Custom Invoice</label>
    <nameField>
        <displayFormat>IN-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Invoices</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Custom_Invoice__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Custom Invoices</relationshipLabel>
    <relationshipName>Custom_Invoices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Custom_Invoice__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Custom Invoices</relationshipLabel>
    <relationshipName>Custom_Invoices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/InvoiceGenartionHandler.cls
public class InvoiceGenartionHandler {
    public static void sendInvoiceEmail(List<Custom_Invoice__c> newRecordList){
        Set<Id> OpportunityIdsSet = new Set<Id>();
        Set<Id> AccountIdsSet = new Set<Id>();
        for (Custom_Invoice__c customInvoice : newRecordList) {
            OpportunityIdsSet.add(customInvoice.Opportunity__c);
            AccountIdsSet.add(customInvoice.Account_Name__c);
        }
        List<Account> accountList = [SELECT Id, Primary_Contact__c FROM Account WHERE Id IN :AccountIdsSet AND Primary_Contact__c != null];
        Map<Id, Account> contactMap = new Map<Id, Account>([SELECT Id, Primary_Contact__r.Email FROM Account WHERE Id IN :AccountIdsSet]);
        List<OpportunityLineItem> OpportunityList = [SELECT Name,Product2.Name, Quantity, UnitPrice, TotalPrice FROM OpportunityLineItem WHERE opportunityId IN :OpportunityIdsSet];
        // Map<Id,Contact> contactMap=new Map<Id,Contact>([Select Id,Email from Contact where Id IN: ContactIdsSet]);
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        for(Custom_Invoice__c customInvoice: newRecordList){
            Account con = contactMap.get(customInvoice.Account_Name__c);
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            mail.setSubject('Invoice Generated ');
            List<String> toAddress = new List<String>();
            toAddress.add(con.Primary_Contact__r.Email);
            mail.setToAddresses( toAddress );
            String table = '<table style="border: 1px solid black; border-collapse: collapse;"><thead style="border: 1px solid black;"><tr><th style="border: 1px solid black;">Product Name</th><th style="border: 1px solid black;">Price</th><th style="border: 1px solid black; ">Quantity</th><th style="border: 1px solid black;">Total Price</th></tr></thead ><tbody style="border: 1px solid black;">';
            for(OpportunityLineItem opp:OpportunityList){   
                table+='<tr><td style="border: 1px solid black;">' + opp.Product2.Name + '</td><td style="border: 1px solid black;">' + opp.UnitPrice + '</td><td style="border: 1px solid black;">' + opp.Quantity + '</td><td style="border: 1px solid black; ">' + opp.TotalPrice + '</td></tr>';
            }
            table+='</tbody></table>';
            mail.setHtmlBody(table);
            emailList.add(mail);
        }
        List<Messaging.SendEmailResult> results=Messaging.sendEmail(emailList,false);
        for(Messaging.SendEmailResult email:results){
            System.debug(email.isSuccess());
        }
    }
    
}